Repository JuulLabs/topaz, pull requests merged in 2025-04, with the labels that each got.

#141 Fix manufacturer and service data filtering for device picker
  lib/Sources/BluetoothAction/Options+Decode.swift
  lib/Tests/BluetoothEngineTests/Options+DecodeTests.swift
Labels: bug

#149 Update to Xcode 16.3
  .xcode-version
  lib/Tests/BluetoothEngineTests/ConnectTests.swift
Labels: maintenance

#148 Adjust client disconnect to use correct event type
  lib/Sources/BluetoothClient/BluetoothClient.swift
  lib/Sources/BluetoothClient/Mocks/MockClient.swift
  lib/Sources/BluetoothNative/NativeClient.swift
  lib/Tests/BluetoothEngineTests/BluetoothEngineTests.swift
Labels: patch

#145 Detailed device picker cancellation error
  lib/Sources/DevicePicker/DeviceSelectionError.swift
  lib/Sources/DevicePicker/DeviceSelector.swift
  lib/Sources/DevicePicker/InteractiveDeviceSelector.swift
  lib/Sources/DevicePicker/TestDeviceSelector.swift
  lib/Tests/DevicePickerTests/DevicePickerTests.swift
Labels: minor

#150 Show bluetooth error banner when in fullscreen
  lib/Sources/App/BluetoothErrorView.swift
  lib/Sources/App/NavBarModel.swift
  lib/Sources/App/NavBarView.swift
  lib/Sources/App/WebContainerModel.swift
  lib/Sources/App/WebContainerView.swift
  lib/Sources/BluetoothEngine/BluetoothSystemState.swift
Labels: minor

#151 Reduce size of navigation title
  lib/Sources/Design/Appearance.swift
  lib/Sources/Design/Dogpatch.swift
Labels: minor

#152 Fine grained bluetooth permissions
  Topaz/TopazMain.swift
  lib/Package.swift
  lib/Sources/App/AppModel.swift
  lib/Sources/App/WebContainerView.swift
  lib/Sources/Permissions/PermissionsModel.swift
  lib/Sources/Permissions/PermissionsView.swift
  lib/Sources/Permissions/Singleton.swift
  lib/Sources/Permissions/WebOrigin.swift
  lib/Sources/Permissions/WebOriginViewModel.swift
  lib/Sources/Settings/SettingsModel.swift
  lib/Sources/Settings/SettingsView.swift
  lib/Sources/WebView/Coordinator.swift
  lib/Sources/WebView/ScriptHandler.swift
  lib/Sources/WebView/WebPageModel.swift
  lib/Sources/WebView/WebPageView.swift
  lib/Tests/PermissionsTests/PermissionsModelTests.swift
Labels: minor
