Repository JuulLabs/topaz, pull requests merged in 2025-03, with the labels that each got.

#123 Select newest iOS simulator explicitly
  .github/workflows/ci.yml
  build.mk
Labels: maintenance

#117 Persist and restore the last tab (or no tab) the user was on
  lib/Sources/App/AppModel.swift
  lib/Sources/App/NavBarModel.swift
  lib/Sources/App/NavBarView.swift
  lib/Sources/App/NavIconStrip.swift
  lib/Sources/App/WebContainerView.swift
  lib/Sources/App/WebLoadingView.swift
  lib/Sources/Tabs/TabGridModel.swift
Labels: minor

#121 Fix bug around activePageModel stack initialization
  lib/Sources/App/AppModel.swift
Labels: patch

#122 Surface options parsing error messages
  lib/Sources/Bluetooth/Options.swift
  lib/Sources/Bluetooth/OptionsError.swift
  lib/Sources/BluetoothAction/RequestDevice.swift
  lib/Sources/BluetoothMessage/JsCodable.swift
  lib/Sources/BluetoothMessage/Message.swift
Labels: patch

#124 Implement Bluetooth.requestLEScan API
  lib/Javascript/src/Bluetooth.ts
  lib/Javascript/src/BluetoothAdvertisingEvent.ts
  lib/Javascript/src/BluetoothLEScan.ts
  lib/Javascript/src/EventSink.ts
  lib/Sources/Bluetooth/BluetoothError.swift
  lib/Sources/Bluetooth/BluetoothLEScan.swift
  lib/Sources/Bluetooth/ServiceData.swift
  lib/Sources/BluetoothAction/AdvertisementEvent+JsEvent.swift
  lib/Sources/BluetoothAction/JsEventForwarder.swift
  lib/Sources/BluetoothAction/Message+Action.swift
  lib/Sources/BluetoothAction/RequestLEScan.swift
  lib/Sources/BluetoothEngine/BluetoothEngine.swift
  lib/Sources/BluetoothEngine/Errors.swift
  lib/Sources/BluetoothMessage/BluetoothState.swift
  lib/Sources/BluetoothMessage/Message.swift
  lib/Sources/BluetoothMessage/ScanTask.swift
  lib/Sources/JsMessage/DomErrorName.swift
  lib/Sources/JsMessage/JsConvertable.swift
  lib/Sources/WebView/Resources/Generated/BluetoothPolyfill.js
  lib/Tests/BluetoothEngineTests/RequestLEScanTests.swift
Labels: minor

#127 Add functionality to clear web caches and cookies
  lib/Sources/Settings/CleanWebCache.swift
  lib/Sources/Settings/SettingsModel.swift
  lib/Sources/Settings/SettingsView.swift
Labels: minor

#125 Implement Bluetooth.getDevices and BluetoothDevice.watchAdvertisements
  lib/Javascript/src/Bluetooth.ts
  lib/Javascript/src/BluetoothAdvertisingEvent.ts
  lib/Javascript/src/BluetoothDevice.ts
  lib/Javascript/src/EventSink.ts
  lib/Javascript/src/Store.ts
  lib/Sources/BluetoothAction/AdvertisementEvent+JsEvent.swift
  lib/Sources/BluetoothAction/Connect.swift
  lib/Sources/BluetoothAction/DiscoverDescriptors.swift
  lib/Sources/BluetoothAction/ForgetDevice.swift
  lib/Sources/BluetoothAction/GetDevices.swift
  lib/Sources/BluetoothAction/Message+Action.swift
  lib/Sources/BluetoothAction/RequestDevice.swift
  lib/Sources/BluetoothAction/RequestLEScan.swift
  lib/Sources/BluetoothAction/WatchAdvertisements.swift
  lib/Sources/BluetoothClient/BluetoothClient.swift
  lib/Sources/BluetoothClient/Mocks/MockClient.swift
  lib/Sources/BluetoothMessage/BluetoothState.swift
  lib/Sources/BluetoothMessage/Message.swift
  lib/Sources/BluetoothMessage/ScanTask.swift
  lib/Sources/BluetoothNative/Coordinator.swift
  lib/Sources/BluetoothNative/NativeClient.swift
  lib/Sources/WebView/Resources/Generated/BluetoothPolyfill.js
  lib/Tests/BluetoothEngineTests/GetDevicesTests.swift
  lib/Tests/BluetoothEngineTests/WatchAdvertisementsTests.swift
Labels: minor

#128 Capture logs via OSLog
  Makefile
  lib/Javascript/src/Bluetooth.ts
  lib/Javascript/src/BluetoothPolyfill.ts
  lib/Javascript/src/Logging.ts
  lib/Javascript/src/Topaz.ts
  lib/Javascript/src/WebKit.ts
  lib/Sources/App/AppModel.swift
  lib/Sources/BluetoothEngine/BluetoothEngine.swift
  lib/Sources/BluetoothMessage/Message.swift
  lib/Sources/Design/Dogpatch.swift
  lib/Sources/Design/FontRegistry.swift
  lib/Sources/Helpers/NSNumber.swift
  lib/Sources/JsMessage/DomError.swift
  lib/Sources/JsMessage/JsConvertable+Debug.swift
  lib/Sources/JsMessage/JsLogger.swift
  lib/Sources/JsMessage/JsType+Debug.swift
  lib/Sources/WebView/Coordinator.swift
  lib/Sources/WebView/Resources/Generated/BluetoothPolyfill.js
  lib/Sources/WebView/ScriptHandler.swift
  lib/Sources/WebView/WebPageView.swift
Labels: minor

#129 Deterministic characteristic instance IDs
  lib/Sources/BluetoothNative/CBCharacteristic.swift
  lib/Sources/BluetoothNative/RelayDelegate.swift
  lib/Sources/Helpers/AssociatedObject.swift
Labels: bug

#133 Propagate unexpected disconnection events
  lib/Sources/BluetoothAction/Disconnect.swift
  lib/Sources/BluetoothAction/JsEvent.swift
  lib/Sources/BluetoothClient/Events/DisconnectionEvent.swift
  lib/Sources/BluetoothEngine/BluetoothEngine.swift
  lib/Sources/BluetoothNative/RelayDelegate.swift
  lib/Tests/BluetoothEngineTests/EndToEndTests.swift
Labels: bug

#132 Persist UUIDs of known devices
  Topaz/TopazMain.swift
  lib/Sources/BluetoothAction/Connect.swift
  lib/Sources/BluetoothAction/ForgetDevice.swift
  lib/Sources/BluetoothAction/GetDevices.swift
  lib/Sources/BluetoothMessage/BluetoothState.swift
  lib/Tests/BluetoothEngineTests/BluetoothStateTests.swift
  lib/Tests/BluetoothEngineTests/EndToEndTests.swift
  lib/Tests/BluetoothEngineTests/GetDevicesTests.swift
Labels: minor

#134 Perform percent string interpolation on Js logs
  lib/Javascript/src/Logging.ts
  lib/Sources/WebView/Resources/Generated/BluetoothPolyfill.js
Labels: minor

#137 Remove unused/outdated functionality from Settings
  lib/Sources/App/AppModel.swift
  lib/Sources/App/NavBarModel.swift
  lib/Sources/App/NavBarView.swift
  lib/Sources/App/NavIconStrip.swift
  lib/Sources/App/WebContainerView.swift
  lib/Sources/App/WebLoadingView.swift
  lib/Sources/Settings/SettingsModel.swift
  lib/Sources/Settings/SettingsView.swift
Labels: minor

#138 Origin aware navigation logic
  lib/Package.swift
  lib/Sources/App/AppModel.swift
  lib/Sources/App/NavBarModel.swift
  lib/Sources/App/SearchBarModel.swift
  lib/Sources/App/SearchBarView.swift
  lib/Sources/Navigation/ErrorDocument.swift
  lib/Sources/Navigation/NavigationEngine+WKNavigationDelegate.swift
  lib/Sources/Navigation/NavigationEngine+WKUIDelegate.swift
  lib/Sources/Navigation/NavigationEngine.swift
  lib/Sources/Navigation/NavigationEngineDelegate.swift
  lib/Sources/Navigation/NavigationItem.swift
  lib/Sources/Navigation/NavigationKind.swift
  lib/Sources/Navigation/NavigationRequest.swift
  lib/Sources/Navigation/SimpleHtmlDocument.swift
  lib/Sources/Navigation/WebNavigator.swift
  lib/Sources/Navigation/WebPageLoadingState.swift
  lib/Sources/Navigation/WebViewObserver.swift
  lib/Sources/WebView/Coordinator+Navigation.swift
  lib/Sources/WebView/Coordinator+UI.swift
  lib/Sources/WebView/Coordinator.swift
  lib/Sources/WebView/WebPageModel.swift
  lib/Sources/WebView/WebPageView.swift
  lib/Tests/NavigationTests/MockAction.swift
  lib/Tests/NavigationTests/MockFrameInfo.swift
  lib/Tests/NavigationTests/NavigationRequestTests.swift
  lib/Tests/NavigationTests/WKSecurityOrigin.swift
Labels: major

#139 Fix bugs with multiple peripherals
  lib/Javascript/src/CharacteristicValueChangedEvent.ts
  lib/Javascript/src/EventSink.ts
  lib/Javascript/src/Logging.ts
  lib/Javascript/src/Store.ts
  lib/Sources/BluetoothAction/DiscoverDescriptors.swift
  lib/Sources/BluetoothAction/ReadCharacteristic.swift
  lib/Sources/BluetoothAction/ReadDescriptor.swift
  lib/Sources/BluetoothAction/RequestDevice.swift
  lib/Sources/BluetoothAction/RequestLEScan.swift
  lib/Sources/BluetoothAction/StartNotifications.swift
  lib/Sources/BluetoothAction/StopNotifications.swift
  lib/Sources/BluetoothAction/WriteCharacteristic.swift
  lib/Sources/BluetoothClient/BluetoothClient.swift
  lib/Sources/BluetoothClient/Events/CharacteristicChangedEvent.swift
  lib/Sources/BluetoothClient/Events/CharacteristicEvent.swift
  lib/Sources/BluetoothClient/Mocks/MockClient.swift
  lib/Sources/BluetoothEngine/BluetoothEngine.swift
  lib/Sources/BluetoothMessage/BluetoothState.swift
  lib/Sources/BluetoothNative/NativeClient.swift
  lib/Sources/BluetoothNative/RelayDelegate.swift
  lib/Sources/WebView/Resources/Generated/BluetoothPolyfill.js
  lib/Tests/BluetoothEngineTests/BluetoothEngineTests.swift
  lib/Tests/BluetoothEngineTests/BluetoothStateTests.swift
  lib/Tests/BluetoothEngineTests/ConnectTests.swift
  lib/Tests/BluetoothEngineTests/DiscoverCharacteristicsTests.swift
  lib/Tests/BluetoothEngineTests/EndToEndTests.swift
  lib/Tests/BluetoothEngineTests/StartNotificationsTests.swift
  lib/Tests/BluetoothEngineTests/StopNotificationsTests.swift
Labels: bug

#140 Allow all non-failure HTTP status codes
  lib/Sources/Navigation/NavigationEngine+WKNavigationDelegate.swift
Labels: patch

#143 Zombie detection and cleanup
  lib/Sources/BluetoothEngine/BluetoothEngine.swift
  lib/Sources/BluetoothEngine/ZombieDetector.swift
  lib/Tests/BluetoothEngineTests/ZombieDetectorTests.swift
Labels: bug
