Repository JuulLabs/topaz, pull requests merged in 2025-02, with the labels that each got.

#105 Update to use GitHub action runners
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .xcode-version
  lib/Sources/BluetoothMessage/BluetoothState.swift
  lib/Sources/Helpers/Debouncer.swift
  lib/Sources/Helpers/DeferredValue.swift
  lib/Sources/Helpers/StateValue.swift
Labels: maintenance

#102 Add license
  LICENSE.txt
  README.md
Labels: maintenance

#101 CA-4125: Filter requestDevices list based on `Options`
  lib/Sources/Bluetooth/Fakes.swift
  lib/Sources/Bluetooth/Options.swift
  lib/Sources/BluetoothAction/Options+Decode.swift
  lib/Sources/BluetoothNative/NativeScanner.swift
  lib/Sources/BluetoothNative/Options+IncludeAdvertisementEvent.swift
  lib/Sources/DevicePicker/MockAdvertisements.swift
  lib/Tests/BluetoothEngineTests/EndToEndTests.swift
  lib/Tests/BluetoothEngineTests/Options+DecodeTests.swift
  lib/Tests/BluetoothNativeTests/Options+IncludeAdvertisementEventTests.swift
  lib/Tests/DevicePickerTests/DevicePickerTests.swift
Labels: minor

#106 CA-3919: Auto load URL if found in clipboard
  lib/Sources/App/AppModel.swift
Labels: minor

#109 CA-4168: Temporarily comment out unfinished UI
  lib/Sources/Settings/SettingsModel.swift
  lib/Sources/Settings/SettingsView.swift
Labels: minor

#108 CA-4172: Fix back button
  lib/Sources/WebView/WebNavigator.swift
Labels: bug

#111 CA-4174: Add tab management features
  lib/Sources/App/AppModel.swift
  lib/Sources/App/NavBarModel.swift
  lib/Sources/App/NavIconStrip.swift
  lib/Sources/App/WebLoadingModel.swift
  lib/Sources/Tabs/TabGridModel.swift
  lib/Sources/Tabs/TabGridView.swift
  lib/Sources/Tabs/TabManagementToolbarView.swift
Labels: minor

#107 CA-4144: Add logic to determine if a user has possibly typed a hostname
  lib/Sources/App/SearchBarModel.swift
  lib/Sources/App/SearchBarView.swift
Labels: minor

#112 Hook up open in new page action
  lib/Sources/App/AppModel.swift
  lib/Sources/App/WebContainerModel.swift
  lib/Sources/App/WebLoadingModel.swift
  lib/Sources/App/WebLoadingView.swift
  lib/Sources/Tabs/TabGridModel.swift
  lib/Sources/WebView/Coordinator+Navigation.swift
  lib/Sources/WebView/Coordinator+UI.swift
  lib/Sources/WebView/Coordinator.swift
  lib/Sources/WebView/WebPageModel.swift
  lib/Sources/WebView/WebPageView.swift
Labels: minor

#118 Allow `optionalServices` with `acceptAllDevices`
  lib/Sources/BluetoothAction/Options+Decode.swift
  lib/Tests/BluetoothEngineTests/Options+DecodeTests.swift
Labels: patch
